--SimpleCRUDDelphiFireDAC

-- TABLE CARGO
CREATE TABLE CARGO(
                    ID INTEGER NOT NULL,
                    DESCRICAO VARCHAR(100), 
                    SALARIO NUMERIC(6,2),
                    CONSTRAINT PK_CARGO PRIMARY KEY(ID)
                    );

CREATE SEQUENCE SEQ_ID_CARGO;

CREATE TRIGGER TR_CARGO FOR CARGO
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_ID_CARGO;
END;

-- TABLE FUNCIONARIO
CREATE TABLE FUNCIONARIO (
                           ID INTEGER NOT NULL,
                           NOME VARCHAR(100), 
                           CPF VARCHAR(20), 
                           RG VARCHAR(20), 
                           ID_CARGO INTEGER,
                           CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID),
                           CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY(ID_CARGO) REFERENCES CARGO(ID)     
                           );

CREATE SEQUENCE SEQ_ID_FUNCIONARIO;

CREATE TRIGGER TR_FUNCIONARIO FOR FUNCIONARIO
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_ID_FUNCIONARIO;
END;

-- TABLE FORNECEDOR
CREATE TABLE FORNECEDOR (
                          CNPJ VARCHAR(20) NOT NULL, 
                          NOME_FANTASIA VARCHAR(100),
                          CONSTRAINT PK_FORNECEDOR PRIMARY KEY(CNPJ)
                          );

-- TABLE PRODUTO
CREATE TABLE PRODUTO (
                       ID INTEGER NOT NULL,
                       DESCRICAO VARCHAR(100),
                       DETALHE VARCHAR(300),
                       PRECO_COMPRA NUMERIC(6,2),
                       PRECO_VENDA NUMERIC(6,2),
                       ID_FORNECEDOR VARCHAR(20),
                       CONSTRAINT PK_PRODUTO PRIMARY KEY(ID),
                       CONSTRAINT FK_PRODUTO_FORNECEDOR FOREIGN KEY(ID_FORNECEDOR) 
                                                          REFERENCES FORNECEDOR(CNPJ)
                       );

CREATE SEQUENCE SEQ_ID_PRODUTO;

CREATE TRIGGER TR_PRODUTO FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_ID_PRODUTO;
END;

-- TABLE USUARIO
CREATE TABLE USUARIO (ID INTEGER NOT NULL,
                       USUARIO VARCHAR(40), 
                       SENHA VARCHAR(20),
                       ID_FUNCIONARIO INTEGER,
                       CONSTRAINT PK_USUARIO PRIMARY KEY(ID),
                       CONSTRAINT FK_USUARIO_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
                       );

CREATE SEQUENCE SEQ_ID_USUARIO;

CREATE TRIGGER TR_USUARIO FOR USUARIO
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_ID_USUARIO;
END;